name: Check Markdown links

on: push

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the code
      uses: actions/checkout@v3
    - name: Check all Markdown files for broken links
      uses: gaurav-nelson/github-action-markdown-link-check@v1
